<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="310387" started-at="2016-05-19T05:42:54Z" finished-at="2016-05-19T05:48:04Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="310387" started-at="2016-05-19T05:42:54Z" finished-at="2016-05-19T05:48:04Z">
      <class name="com.ibm.test.Demo">
        <test-method status="PASS" signature="bTest()[pri:0, instance:com.ibm.test.Demo@d7b1517]" name="bTest" is-config="true" duration-ms="556" started-at="2016-05-19T13:42:54Z" finished-at="2016-05-19T13:42:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- bTest -->
        <test-method status="PASS" signature="bClass()[pri:0, instance:com.ibm.test.Demo@d7b1517]" name="bClass" is-config="true" duration-ms="0" started-at="2016-05-19T13:42:55Z" finished-at="2016-05-19T13:42:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- bClass -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.ibm.test.Demo@d7b1517]" name="setUp" is-config="true" duration-ms="97404" started-at="2016-05-19T13:42:55Z" finished-at="2016-05-19T13:44:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="loginTest()[pri:0, instance:com.ibm.test.Demo@d7b1517]" name="loginTest" duration-ms="114803" started-at="2016-05-19T13:44:32Z" finished-at="2016-05-19T13:46:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="FAIL" signature="selectSeats()[pri:0, instance:com.ibm.test.Demo@d7b1517]" name="selectSeats" duration-ms="79757" started-at="2016-05-19T13:46:27Z" depends-on-methods="com.ibm.test.Demo.loginTest" finished-at="2016-05-19T13:47:47Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Get Text from WebElement By.xpath: .//*[@id='accountdetails']/p[1], Failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Get Text from WebElement By.xpath: .//*[@id='accountdetails']/p[1], Failed
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.asserts.Assertion$6.doAssert(Assertion.java:185)
	at org.testng.asserts.Assertion.executeAssert(Assertion.java:30)
	at org.testng.asserts.Assertion.doAssert(Assertion.java:15)
	at org.testng.asserts.Assertion.fail(Assertion.java:182)
	at com.bailian.ta.action.FrameAssertion.fail(FrameAssertion.java:13)
	at com.bailian.ta.action.FrameAction.getText(FrameAction.java:110)
	at com.ibm.test.Demo.selectSeats(Demo.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- selectSeats -->
        <test-method status="PASS" signature="aClass()[pri:0, instance:com.ibm.test.Demo@d7b1517]" name="aClass" is-config="true" duration-ms="10250" started-at="2016-05-19T13:47:48Z" finished-at="2016-05-19T13:47:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aClass -->
        <test-method status="PASS" signature="aTest()[pri:0, instance:com.ibm.test.Demo@d7b1517]" name="aTest" is-config="true" duration-ms="6606" started-at="2016-05-19T13:47:58Z" finished-at="2016-05-19T13:48:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aTest -->
      </class> <!-- com.ibm.test.Demo -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
